
#ifndef b4r_convert_h
#define b4r_convert_h
class b4r_main;

class b4r_convert {
public:

static B4R::Array* _appendxorchecksum(B4R::Array* _frame);
static Int _asciibuffertoint(B4R::Array* _buffer);
static bool _asciibytestobool(B4R::Array* _bytes);
static bool _asciibytetobool(Byte _b);
static Int _asciibytetoint(B4R::Array* _bytes);
static UInt _bcdarraytouint(B4R::Array* _b);
static UInt _bcdtobyte(Byte _b);
static UInt _bintodec(B4R::B4RString* _binstr);
static Byte _booltobyte(bool _state);
static B4R::B4RString* _booltoonoff(bool _state);
static B4R::B4RString* _booltostring(bool _state);
static B4R::Array* _bytestobin(B4R::Array* _bytes);
static B4R::Array* _bytestobitsstring(B4R::Array* _bytes);
static Double _bytestofloat(B4R::Array* _b);
static Double _bytestofloatscaled(B4R::Array* _b,Byte _fractions);
static B4R::B4RString* _bytestohex(B4R::Array* _bytes);
static B4R::B4RString* _bytestostring(B4R::Array* _bytes);
static ULong _bytestouint(B4R::Array* _b);
static UInt _bytestouint16swapped(B4R::Array* _b);
static ULong _bytestouint32swapped(B4R::Array* _b);
static ULong _bytestoulong(B4R::Array* _b);
static UInt _bytetobcd(Byte _value);
static B4R::B4RString* _bytetobcdbin(Byte _value);
static B4R::Array* _bytetobin(Byte _b);
static B4R::Array* _bytetobitsstring(Byte _b);
static bool _bytetobool(Byte _b);
static B4R::B4RString* _bytetohex(Byte _b);
static B4R::Array* _colortorgb(ULong _color);
static B4R::B4RString* _csvcheckvalue(B4R::Array* _item,Int _index,B4R::B4RString* _tag);
static Int _csvcountitems(B4R::Array* _buffer,B4R::B4RString* _separator);
static B4R::Array* _csvtobytes(B4R::Array* _buffer,B4R::B4RString* _separator);
static B4R::Array* _csvtofloats(B4R::Array* _buffer,B4R::B4RString* _separator);
static B4R::Array* _csvtoints(B4R::Array* _buffer,B4R::B4RString* _separator);
static B4R::Array* _csvtouints(B4R::Array* _buffer,B4R::B4RString* _separator);
static B4R::Array* _csvtoulongs(B4R::Array* _buffer,B4R::B4RString* _separator);
static B4R::B4RString* _directiontostring(Byte _direction);
static bool _equalsignorecase(B4R::B4RString* _s1,B4R::B4RString* _s2);
static B4R::Array* _floattobytes(Double _f);
static bool _getbit(Byte _b,Int _index);
static bool _inttobool(Int _value);
static B4R::B4RString* _millistobytes(Long _ms);
static B4R::Array* _modbuscrc16(B4R::Array* _frame);
static bool _modbuscrc16check(B4R::Array* _frame);
static B4R::Array* _modbuscrc16transmittedframe(B4R::Array* _frame);
static ULong _modbuscrc16uint(B4R::Array* _frame);
static B4R::B4RString* _nibbletobin(Byte _nibble);
static bool _onofftobool(B4R::B4RString* _value);
static void _process_globals();
static ULong _version;
static Byte _byte_min;
static Byte _byte_max;
static Int _int16_min;
static Int _int16_max;
static ULong _uint16_min;
static ULong _uint16_max;
static ULong _uint32_min;
static ULong _uint32_max;
static Double _float_min;
static Double _float_max;
static Double _double_min;
static Double _double_max;
static ULong _modbus_polynomial;
static bool _splitallowemptyaszero;
static B4R::ByteConverter* _byteconv;
static b4r_main* _main;
static B4R::Array* _replacestring(B4R::Array* _original,B4R::Array* _searchfor,B4R::Array* _replacewith);
static B4R::Array* _reversebytes(B4R::Array* _b);
static ULong _rgbtocolor(Byte _r,Byte _g,Byte _b);
static Byte _setbit(Byte _b,Int _index,bool _on);
static B4R::B4RString* _stringtrim(B4R::B4RString* _s);
static B4R::B4RString* _stringtrimcrlf(B4R::B4RString* _s);
static UInt _swapuint16(UInt _value);
static B4R::Array* _swapuint16tobytes(UInt _value);
static ULong _swapuint32(ULong _value);
static B4R::Array* _swapuint32tobytes(ULong _value);
static Byte _togglebit(Byte _b,Int _index);
static B4R::B4RString* _tolowercase(B4R::B4RString* _s);
static B4R::B4RString* _touppercase(B4R::B4RString* _s);
static B4R::B4RString* _twobytestohex(Byte _b1,Byte _b2);
static Int _twobytestoint(B4R::Array* _b,bool _littleendian);
static UInt _twobytestouint(B4R::Array* _b,bool _littleendian);
static UInt _uintfromstring(B4R::Array* _s);
static B4R::Array* _uinttobcdarray(ULong _value);
static B4R::Array* _uinttobytes(ULong _value);
static B4R::Array* _uinttobytesendian(ULong _value,bool _littleendian);
static B4R::B4RString* _uinttohex(UInt _value);
static UInt _ulongfromstring(B4R::Array* _s);
static B4R::Array* _ulongtobytes(ULong _value);
static B4R::B4RString* _ulongtohex(ULong _value);
static Byte _xorchecksum(B4R::Array* _b);
};

#endif